# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/psf/Home/Documents/GitHub/SELab_22Fall

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/psf/Home/Documents/GitHub/SELab_22Fall

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/psf/Home/Documents/GitHub/SELab_22Fall/CMakeFiles /media/psf/Home/Documents/GitHub/SELab_22Fall/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/psf/Home/Documents/GitHub/SELab_22Fall/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SELab_22Fall

# Build rule for target.
SELab_22Fall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SELab_22Fall
.PHONY : SELab_22Fall

# fast build rule for target.
SELab_22Fall/fast:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/build
.PHONY : SELab_22Fall/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/main.cpp.s
.PHONY : main.cpp.s

src/execute.o: src/execute.cpp.o

.PHONY : src/execute.o

# target to build an object file
src/execute.cpp.o:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/src/execute.cpp.o
.PHONY : src/execute.cpp.o

src/execute.i: src/execute.cpp.i

.PHONY : src/execute.i

# target to preprocess a source file
src/execute.cpp.i:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/src/execute.cpp.i
.PHONY : src/execute.cpp.i

src/execute.s: src/execute.cpp.s

.PHONY : src/execute.s

# target to generate assembly for a file
src/execute.cpp.s:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/src/execute.cpp.s
.PHONY : src/execute.cpp.s

src/input.o: src/input.cpp.o

.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i

.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s

.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/judge.o: src/judge.cpp.o

.PHONY : src/judge.o

# target to build an object file
src/judge.cpp.o:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/src/judge.cpp.o
.PHONY : src/judge.cpp.o

src/judge.i: src/judge.cpp.i

.PHONY : src/judge.i

# target to preprocess a source file
src/judge.cpp.i:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/src/judge.cpp.i
.PHONY : src/judge.cpp.i

src/judge.s: src/judge.cpp.s

.PHONY : src/judge.s

# target to generate assembly for a file
src/judge.cpp.s:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/src/judge.cpp.s
.PHONY : src/judge.cpp.s

src/output.o: src/output.cpp.o

.PHONY : src/output.o

# target to build an object file
src/output.cpp.o:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/src/output.cpp.o
.PHONY : src/output.cpp.o

src/output.i: src/output.cpp.i

.PHONY : src/output.i

# target to preprocess a source file
src/output.cpp.i:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/src/output.cpp.i
.PHONY : src/output.cpp.i

src/output.s: src/output.cpp.s

.PHONY : src/output.s

# target to generate assembly for a file
src/output.cpp.s:
	$(MAKE) -f CMakeFiles/SELab_22Fall.dir/build.make CMakeFiles/SELab_22Fall.dir/src/output.cpp.s
.PHONY : src/output.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... SELab_22Fall"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/execute.o"
	@echo "... src/execute.i"
	@echo "... src/execute.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/judge.o"
	@echo "... src/judge.i"
	@echo "... src/judge.s"
	@echo "... src/output.o"
	@echo "... src/output.i"
	@echo "... src/output.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

